spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hyperativa
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/migration,classpath:db/migration-local
    baselineOnMigrate: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    root: INFO
    com:
      hyperativatechtest: DEBUG
    org:
      springframework:
        security: DEBUG
      flywaydb: DEBUG

springdoc:
  swagger-ui:
    enabled: true

server:
  port: 8080

jwt:
  secret: mySecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong123456789
  expiration: 86400000

aws:
  s3:
    endpoint: http://localhost:4566
    region: us-east-1
    access-key: test
    secret-key: test
    bucket-name: cards-bucket

encryption:
  secret: AES256SecretKeyForCardEncryption!

aws:
  region: us-east-1
  endpoint: http://localhost:4566
  access-key: test
  secret-key: test
  s3:
    bucket: card-files-bucket
    presigned-url-expiration: 3600

